In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv(r"C:\Users\srich\OneDrive\Desktop\Technical\Projects\Internships\1M1B Virtual Internship\CleanGanga-Prayagraj\data\Prayagraj_Data.csv")
df.shape  # Number of rows and columns in a tuple.
# Display the names of all columns in the dataset.
# .tolist() converts the Pandas Index containing column names into a normal Python list.
df.columns.tolist()  
# Display detailed information about the DataFrame.
df.info()
# Non-null count says how many cells are  not missing
# Display the first 5 rows of the dataset.
# This helps us understand what one actual observation looks like.
df.head()
# Display the last 5 rows of the dataset.
# This allows us to check the end of the dataset and make sure
# the data appears to have been loaded correctly.
df.tail()

<class 'pandas.DataFrame'>
RangeIndex: 1414 entries, 0 to 1413
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   SlNo                              1414 non-null   int64
 1   Station                           1414 non-null   str
 2   Agency                            1414 non-null   str
 3   State LGD Code                    1414 non-null   int64
 4   State                             1414 non-null   str
 5   District LGD Code                 1414 non-null   int64
 6   District                          1414 non-null   str
 7   Tehsil                            1414 non-null   str
 8   Block                             1414 non-null   str
 9   Village                           1414 non-null   str
 10  River                             1414 non-null   str
 11  Basin                             1414 non-null   str
 12  Tributary                         1414 non-null   str
 13  Subtributary                      1414 non-null   str
 14  SubSubtributary                   1414 non-null   str
 15  Local River                       1414 non-null   str
 16  Latitude                          1414 non-null   float64
 17  Longitude                         1414 non-null   float64
 18  Data Acquisition Time             1414 non-null   str
 19  Biochemical Oxygen Demand (mg/L)  1279 non-null   float64
 20  Chemical Oxygen Demand (mg/L)     0 non-null      float64
 21  Fecal Coliform (MPN/100mL)        1264 non-null   float64
 22  Total Coliform (MPN/100mL)        30 non-null     float64
dtypes: float64(6), int64(3), str(14)
memory usage: 254.2 KB

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,...,Subtributary,SubSubtributary,Local River,Latitude,Longitude,Data Acquisition Time,Biochemical Oxygen Demand (mg/L),Chemical Oxygen Demand (mg/L),Fecal Coliform (MPN/100mL),Total Coliform (MPN/100mL)
1409,1410,YAMUNA AT VISHRAMGHAT MATHURA,CPCB,9,Uttar Pradesh,167,MATHURA,MATHURA,-,-,...,-,-,-,27.504755,77.686524,05-08-2021 08:30,9.8,NaN,47000.0,NaN
1410,1411,YAMUNA AT VISHRAMGHAT MATHURA,CPCB,9,Uttar Pradesh,167,MATHURA,MATHURA,-,-,...,-,-,-,27.504755,77.686524,08-09-2021 08:30,8.2,NaN,31000.0,NaN
1411,1412,YAMUNA AT VISHRAMGHAT MATHURA,CPCB,9,Uttar Pradesh,167,MATHURA,MATHURA,-,-,...,-,-,-,27.504755,77.686524,11-10-2021 08:30,9.0,NaN,33000.0,NaN
1412,1413,YAMUNA AT VISHRAMGHAT MATHURA,CPCB,9,Uttar Pradesh,167,MATHURA,MATHURA,-,-,...,-,-,-,27.504755,77.686524,06-11-2021 08:30,10.8,NaN,43000.0,NaN
1413,1414,YAMUNA AT VISHRAMGHAT MATHURA,CPCB,9,Uttar Pradesh,167,MATHURA,MATHURA,-,-,...,-,-,-,27.504755,77.686524,06-12-2021 08:30,10.6,NaN,33000.0,NaN

In [5]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nDistricts:")
print(df["District"].unique()) # unique values

print("\nStations:")
print(df["Station"].nunique()) # number of unique values

Shape: (1414, 23)

Columns:
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Biochemical Oxygen Demand (mg/L)', 'Chemical Oxygen Demand (mg/L)', 'Fecal Coliform (MPN/100mL)', 'Total Coliform (MPN/100mL)']

Districts:
<StringArray>
[         'G.B. Nagar',       'MUZAFFARNAGAR',             'BAGHPAT',
            'HAMIRPUR',              'JHANSI',              'RAMPUR',
           'MORADABAD',           'Allahabad',        'KANPUR NAGAR',
           'Raibareli', 'JYOTIBA PHULE NAGAR',              'BUDAUN',
          'PRATAPGARH',             'KANNAUJ',              'HARDOI',
               'UNNAO',       'Buland Shahar',            'GHAZIPUR',
            'VARANASI',            'MIRZAPUR',              'DEORIA',
             'JAUNPUR',             'LUCKNOW',             'SITAPUR',
            'LALITPUR',           'GHAZIABAD',              'JALAUN',
              'BIJNOR',           'GORAKHPUR',           'SONBHADRA',
  'SANT RAVIDAS NAGAR',         'FARRUKHABAD',           'BARABANKI',
             'Ayodhya',               'KHERI',              'MEERUT',
                'AGRA',              'ETAWAH',             'AURAIYA',
             'MATHURA']
Length: 40, dtype: str

Stations:
131

In [18]:
for col in df.columns:
    print(col)
df["District"].unique()

SlNo
Station
Agency
State LGD Code
State
District LGD Code
District
Tehsil
Block
Village
River
Basin
Tributary
Subtributary
SubSubtributary
Local River
Latitude
Longitude
Data Acquisition Time
Biochemical Oxygen Demand (mg/L)
Chemical Oxygen Demand (mg/L)
Fecal Coliform (MPN/100mL)
Total Coliform (MPN/100mL)

<StringArray>
[         'G.B. Nagar',       'MUZAFFARNAGAR',             'BAGHPAT',
            'HAMIRPUR',              'JHANSI',              'RAMPUR',
           'MORADABAD',           'Allahabad',        'KANPUR NAGAR',
           'Raibareli', 'JYOTIBA PHULE NAGAR',              'BUDAUN',
          'PRATAPGARH',             'KANNAUJ',              'HARDOI',
               'UNNAO',       'Buland Shahar',            'GHAZIPUR',
            'VARANASI',            'MIRZAPUR',              'DEORIA',
             'JAUNPUR',             'LUCKNOW',             'SITAPUR',
            'LALITPUR',           'GHAZIABAD',              'JALAUN',
              'BIJNOR',           'GORAKHPUR',           'SONBHADRA',
  'SANT RAVIDAS NAGAR',         'FARRUKHABAD',           'BARABANKI',
             'Ayodhya',               'KHERI',              'MEERUT',
                'AGRA',              'ETAWAH',             'AURAIYA',
             'MATHURA']
Length: 40, dtype: str

In [19]:
prayagraj = df[df["District"] == "Allahabad"].copy()
print("Prayagraj records:", len(prayagraj)) # Total number of observations in Prayagraj Dataset.
print("Stations:", prayagraj["Station"].nunique())

print("\nObservations per station:")
# .value_counts() counts how many times each
# unique station name appears.
print(prayagraj["Station"].value_counts())

Prayagraj records: 116
Stations: 6

Observations per station:
Station
GANGA AT ALLAHABAD D/S (SANGAM) U.P.           24
GANGA AT ALLAHABAD (RASOOLABAD) U.P.           24
GANGA AT KADAGHAT ALLAHABAD                    24
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA    24
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P       11
TONS AT CHAKGHAT M.P.                           9
Name: count, dtype: int64

In [10]:
print(df.columns[18:].tolist())
prayagraj[df.columns[18:]].describe()
# Count the number of missing values (NaN) in each
# selected water-quality column.
# .isna() identifies missing values.
# .sum() counts those missing values for each column.
# This is important because a missing measurement should
# NOT be treated as zero pollution.
prayagraj[df.columns[18:]].isna().sum()

['Data Acquisition Time', 'Biochemical Oxygen Demand (mg/L)', 'Chemical Oxygen Demand (mg/L)', 'Fecal Coliform (MPN/100mL)', 'Total Coliform (MPN/100mL)']

Data Acquisition Time                 0
Biochemical Oxygen Demand (mg/L)      1
Chemical Oxygen Demand (mg/L)       116
Fecal Coliform (MPN/100mL)            8
Total Coliform (MPN/100mL)          116
dtype: int64

In [15]:
# Manually checking why KeyError occured 
# Learnt that Pandas is case sensitive.
cols = [
    "Station",
    "Data Acquisition Time",
    "Biochemical Oxygen Demand (mg/L)",
    "Fecal Coliform (MPN/100ml)"
]

for col in cols:
    print(repr(col), "->", col in prayagraj.columns)
[c for c in prayagraj.columns if "Fecal" in c]
print(prayagraj.columns.tolist())

'Station' -> True
'Data Acquisition Time' -> True
'Biochemical Oxygen Demand (mg/L)' -> True
'Fecal Coliform (MPN/100ml)' -> False
['SlNo', 'Station', 'Agency', 'State LGD Code', 'State', 'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River', 'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River', 'Latitude', 'Longitude', 'Data Acquisition Time', 'Biochemical Oxygen Demand (mg/L)', 'Chemical Oxygen Demand (mg/L)', 'Fecal Coliform (MPN/100mL)', 'Total Coliform (MPN/100mL)']

In [ ]:
parameters = [
    "Biochemical Oxygen Demand (mg/L)",
    "Fecal Coliform (MPN/100mL)"   # Corrected small case 'l' to large case to match with the original data.
]

prayagraj[["Station", "Data Acquisition Time"] + parameters].head(20)
prayagraj[parameters].describe()
prayagraj.groupby("Station")[parameters].agg(["count", "mean", "max"])

                                            Biochemical Oxygen Demand (mg/L)  \
                                                                       count
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.                                      24
GANGA AT ALLAHABAD D/S (SANGAM) U.P.                                      24
GANGA AT KADAGHAT ALLAHABAD                                               23
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA                               24
TONS AT CHAKGHAT M.P.                                                      9
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P                                  11

                                                            \
                                                 mean  max
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.         2.733333  2.9
GANGA AT ALLAHABAD D/S (SANGAM) U.P.         2.675000  2.9
GANGA AT KADAGHAT ALLAHABAD                  2.660870  2.9
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA  2.625000  2.8
TONS AT CHAKGHAT M.P.                        1.688889  2.0
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P     2.545455  2.7

                                            Fecal Coliform (MPN/100mL)  \
                                                                 count
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.                                23
GANGA AT ALLAHABAD D/S (SANGAM) U.P.                                23
GANGA AT KADAGHAT ALLAHABAD                                         23
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA                         23
TONS AT CHAKGHAT M.P.                                                5
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P                            11


                                                    mean     max
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.         1003.913043  1400.0
GANGA AT ALLAHABAD D/S (SANGAM) U.P.         1011.739130  1400.0
GANGA AT KADAGHAT ALLAHABAD                   928.695652  1400.0
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA   792.173913  1100.0
TONS AT CHAKGHAT M.P.                           2.000000     2.0
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P      654.545455   930.0

ERROR OCCURED: Here 'KeyError' occured with Fecal Coliform (MPN/100ml) and Fecal Coliform (MPN/100mL) 

SOLUTION OFFERED: Checked the error and modified it.

In [ ]:
# BASIC POLLUTION DATA EXPLORATION
# These are the two parameters that currently contain usable observations in our Prayagraj data.
parameters = [
    "Biochemical Oxygen Demand (mg/L)",
    "Fecal Coliform (MPN/100mL)"
]

# Show basic statistics for each parameter.
# count  = number of available measurements
# mean   = average
# std    = variation
# min    = minimum
# 25%    = lower quartile
# 50%    = median
# 75%    = upper quartile
# max    = maximum

print("Pollution Parameter Statistics ")
display(prayagraj[parameters].describe())

# Check how many values are missing.
print("\n Missing Values")
print(prayagraj[parameters].isna().sum())

Pollution Parameter Statistics

       Biochemical Oxygen Demand (mg/L)  Fecal Coliform (MPN/100mL)
count                        115.000000                  108.000000
mean                           2.584348                  862.500000
std                            0.318877                  294.255674
min                            1.100000                    2.000000
25%                            2.600000                  707.500000
50%                            2.700000                  825.000000
75%                            2.800000                 1100.000000
max                            2.900000                 1400.000000

 Missing Values
Biochemical Oxygen Demand (mg/L)    1
Fecal Coliform (MPN/100mL)          8
dtype: int64

In [30]:
# Looking at the actual measurements
display( prayagraj[["Station", "Data Acquisition Time"] + parameters].sort_values("Data Acquisition Time"))

,Station,Data Acquisition Time,Biochemical Oxygen Demand (mg/L),Fecal Coliform (MPN/100mL)
85,GANGA AT ALLAHABAD D/S (SANGAM) U.P.,04-01-2021 08:30,2.0,790.0
814,RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA,04-01-2021 08:30,2.2,1100.0
207,GANGA AT KADAGHAT ALLAHABAD,04-01-2021 08:30,2.0,1300.0
1293,YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P,04-01-2021 08:30,1.9,780.0
1268,TONS AT CHAKGHAT M.P.,04-01-2021 08:30,2.0,2.0
...,...,...,...,...
118,GANGA AT ALLAHABAD (RASOOLABAD) U.P.,31-05-2021 08:30,2.9,1400.0
833,RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA,31-10-2021 08:30,2.6,930.0
128,GANGA AT ALLAHABAD (RASOOLABAD) U.P.,31-10-2021 08:30,2.6,780.0
226,GANGA AT KADAGHAT ALLAHABAD,31-10-2021 08:30,2.6,710.0
104,GANGA AT ALLAHABAD D/S (SANGAM) U.P.,31-10-2021 08:30,2.8,1100.0

In [31]:
# Pollution categorised by each station
station_summary = (prayagraj.groupby("Station")[parameters].agg(["count", "mean", "median", "max"]))
display(station_summary)

                                            Biochemical Oxygen Demand (mg/L)  \
                                                                       count
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.                                      24
GANGA AT ALLAHABAD D/S (SANGAM) U.P.                                      24
GANGA AT KADAGHAT ALLAHABAD                                               23
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA                               24
TONS AT CHAKGHAT M.P.                                                      9
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P                                  11

                                                                   \
                                                 mean median  max
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.         2.733333    2.8  2.9
GANGA AT ALLAHABAD D/S (SANGAM) U.P.         2.675000    2.7  2.9
GANGA AT KADAGHAT ALLAHABAD                  2.660870    2.7  2.9
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA  2.625000    2.7  2.8
TONS AT CHAKGHAT M.P.                        1.688889    1.7  2.0
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P     2.545455    2.6  2.7

                                            Fecal Coliform (MPN/100mL)  \
                                                                 count
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.                                23
GANGA AT ALLAHABAD D/S (SANGAM) U.P.                                23
GANGA AT KADAGHAT ALLAHABAD                                         23
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA                         23
TONS AT CHAKGHAT M.P.                                                5
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P                            11


                                                    mean median     max
Station
GANGA AT ALLAHABAD (RASOOLABAD) U.P.         1003.913043  930.0  1400.0
GANGA AT ALLAHABAD D/S (SANGAM) U.P.         1011.739130  930.0  1400.0
GANGA AT KADAGHAT ALLAHABAD                   928.695652  840.0  1400.0
RIVER GANGA A/C TAMSA RIVER SIRSA SON BARSA   792.173913  790.0  1100.0
TONS AT CHAKGHAT M.P.                           2.000000    2.0     2.0
YAMUNA AT ALLAHABAD D/S (BALUA GHAT) U.P      654.545455  680.0   930.0

For BOD we have one clear threshold:
BOD ≤ 3 mg/L       → within criterion
BOD > 3 mg/L       → exceeds criterion

For Fecal Coliform:
FC ≤ 500            → desirable
500 < FC ≤ 2500     → above desirable, but within maximum permissible
FC > 2500           → exceeds maximum permissible

# CPCB Class B bathing-water criteria
BOD_LIMIT = 3                  # mg/L
FC_DESIRABLE = 500             # MPN/100 mL
FC_MAX = 2500                  # MPN/100 mL

# Check whether each observation exceeds the BOD criterion.
prayagraj["BOD_exceeds"] = (prayagraj["Biochemical Oxygen Demand (mg/L)"] >BOD_LIMIT)

# Check whether Fecal Coliform exceeds the desirable level.
prayagraj["FC_above_desirable"] = ( prayagraj["Fecal Coliform (MPN/100ml)"] > FC_DESIRABLE)

# Check whether Fecal Coliform exceeds the maximum permissible level.
prayagraj["FC_exceeds_max"] = (prayagraj["Fecal Coliform (MPN/100ml)"] > FC_MAX)

# Display the result so we can inspect individual observations.
display(prayagraj[["Station","Biochemical Oxygen Demand (mg/L)","Fecal Coliform (MPN/100ml)","BOD_exceeds","FC_above_desirable","FC_exceeds_max"]])